services:
  db:
    image: postgres:15-alpine
    container_name: photoshare_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret_password
      POSTGRES_DB: photoshare_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - photoshare_net
    restart: always

  redis:
    image: redis:7-alpine
    container_name: photoshare_redis
    ports:
      - "6379:6379"
    networks:
      - photoshare_net
    restart: always

  web:
    build: .
    container_name: photoshare_web
    ports:
      - "8000:8000"
    # Docker сам зчитає ваш локальний .env і прокине змінні у web
    env_file:
      - .env
    environment:
      # Перекриваємо тільки хост бази даних, бо всередині докера він має назву db:5432
      - DATABASE_URL=postgresql+psycopg2://postgres:secret_password@db:5432/photoshare_db
      - REDIS_HOST=redis
    depends_on:
      - db
      - redis
    networks:
      - photoshare_net
    restart: always

volumes:
  postgres_data:

networks:
  photoshare_net:
    driver: bridge
