"""Add is_confirmed to users

Revision ID: 7d6af34f6a28
Revises: f920303603b3
Create Date: 2026-09-04 16:14:26.987391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d6af34f6a28'
down_revision: Union[str, Sequence[str], None] = 'f920303603b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. Створюємо колонку, але тимчасово дозволяємо NULL (nullable=True)
    op.add_column('users', sa.Column('is_confirmed', sa.Boolean(), nullable=True))
    
    # 2. Проставляємо всім існуючим користувачам значення True (щоб вони не були заблоковані)
    op.execute("UPDATE users SET is_confirmed = True")
    
    # 3. Тепер суворо змінюємо колонку на nullable=False
    op.alter_column('users', 'is_confirmed', nullable=False)



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_confirmed')
    # ### end Alembic commands ###
